title: Rahul Pande
email: 93.rahulpande@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning | Analytics | Data Engineering. I often tweak custom Android ROMs.
author: Rahul Pande
logo: /static/img/avatar.png
github: https://github.com/rahul-pande
about: Data Science Masters Student

baseurl: ""
url: "https://rahulpande.me"

allowsearch: true

disqus_shortname: rahulpande-me
google_analytics: UA-109424948-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
